{
 "title": "Grafana Dashboard for Cloudflare Analytics and Overview",
 "description": "Grafana Dashboard for Cloudflare Analytics and Overview",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "ZONE",
    "query": "show tag values from cloudflare_analytics with key = \"cfZone\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfThreatsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfUniquesAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Countries Traffic Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_country",
     "select": [
      [
       { "params": [ "visits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Countries Threat Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_country",
     "select": [
      [
       { "params": [ "threats" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Cached Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    },
    {
     "alias": "Uncached Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfBandwidthUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uncached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Through Cloudflare",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cached Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone$/" }
     ]
    },
    {
     "alias": "Uncached Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfRequestsUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uncached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cfZone", "operator": "=~", "value": "/^$zone_id$/" }
     ]
    }
   ]
  }
 ]
}