{
 "title": "Grafana Dashboard for Cloudflare Analytics and Overview",
 "description": "Grafana Dashboard for Cloudflare - Pulls out all the Cloudflare Information, and Analytics from the RESTful API.",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Threats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfThreatsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfUniquesAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Countries Traffic Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_country",
     "select": [
      [
       { "params": [ "visits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uncached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfRequestsUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Through Cloudflare",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cached Requests",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfRequestsCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached Requests" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Uncached Requests",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfRequestsUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uncached Requests" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthAll" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "cfBandwidthUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Cached Bandwidth",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfBandwidthCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached Requests" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Uncached Bandwidth",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cfBandwidthUncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uncached Requests" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 21 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}